### ISSUE TITLE
Online web demo 

### ISSUE THREAD

**Issue by yuchenlin** [yuchenlin/rebiber#10]
Work in progress and suggestions are welcome!

**Comment by huybery** [comment]
Could u share some TODO feature for web demo ? 
I'm very interested in this project and have had an idea for a long time, but no time to realize it because of busy work

**Comment by yuchenlin** [comment]
https://colab.research.google.com/drive/12oQcLs25CFjI4evsFlWfKD1DfTEiqyCN?usp=sharing

**Comment by yuchenlin** [comment]
Our web demo is online here: http://rebiber.herokuapp.com/
