### ISSUE TITLE
Comments in bib file are transformed into `@comments`

### ISSUE THREAD

**Issue by boredtylin** [yuchenlin/rebiber#22]
I come across two issues here:

- [ ] Somehow the tool transforms my comments (ones starting with `%`) in bib file into `@comment{}` and places them at the head of the file;
- [ ] All the bibs are by default organized in an alphabetic manner, is there a way (option) I can remain the order of bibs (and thus keep the comments where they are) .

Great tool by the way :)

**Comment by mpariente** [comment]
I second this. 
The most important to my eyes is to keep the git diff as small as possible, so that we can easily inspect was has been updated.

**Comment by mpariente** [comment]
About the sorting, of the entries this patch solves it
```diff
Index: rebiber/normalize.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/rebiber/normalize.py b/rebiber/normalize.py
--- a/rebiber/normalize.py	(revision 3c46fd379a3da5414403d9ef5ffc695bafccd4b3)
+++ b/rebiber/normalize.py	(date 1625041178058)
@@ -1,3 +1,4 @@
+from bibtexparser.bwriter import BibTexWriter
 import rebiber
 from rebiber.bib2json import normalize_title, load_bib_file
 import argparse
@@ -34,7 +35,7 @@
             return True
     return False
 
-def post_processing(output_bib_entries, removed_value_names, abbr_dict):
+def post_processing(output_bib_entries, removed_value_names, abbr_dict, sort=False):
     bibparser = bibtexparser.bparser.BibTexParser(ignore_nonstandard_types=False)
     bib_entry_str = ""
     for entry in output_bib_entries:
@@ -64,7 +65,10 @@
                     if re.match(pattern, output_entry[place]):
                         output_entry[place] = short
 
-    return bibtexparser.dumps(parsed_entries)
+    writer = BibTexWriter()
+    if not sort:
+        writer.order_entries_by = None
+    return bibtexparser.dumps(parsed_entries, writer=writer)
 
 
 def normalize_bib(bib_db, all_bib_entries, output_bib_path, deduplicate=True, removed_value_names=[], abbr_dict={}):
```

but the order within entries is not conserved so the diffs are still huge even if nothing changed.

**Comment by yangxqiao** [comment]
> About the sorting, of the entries this patch solves it
> 
> ```diff
> Index: rebiber/normalize.py
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/rebiber/normalize.py b/rebiber/normalize.py
> --- a/rebiber/normalize.py	(revision 3c46fd379a3da5414403d9ef5ffc695bafccd4b3)
> +++ b/rebiber/normalize.py	(date 1625041178058)
> @@ -1,3 +1,4 @@
> +from bibtexparser.bwriter import BibTexWriter
>  import rebiber
>  from rebiber.bib2json import normalize_title, load_bib_file
>  import argparse
> @@ -34,7 +35,7 @@
>              return True
>      return False
>  
> -def post_processing(output_bib_entries, removed_value_names, abbr_dict):
> +def post_processing(output_bib_entries, removed_value_names, abbr_dict, sort=False):
>      bibparser = bibtexparser.bparser.BibTexParser(ignore_nonstandard_types=False)
>      bib_entry_str = ""
>      for entry in output_bib_entries:
> @@ -64,7 +65,10 @@
>                      if re.match(pattern, output_entry[place]):
>                          output_entry[place] = short
>  
> -    return bibtexparser.dumps(parsed_entries)
> +    writer = BibTexWriter()
> +    if not sort:
> +        writer.order_entries_by = None
> +    return bibtexparser.dumps(parsed_entries, writer=writer)
>  
>  
>  def normalize_bib(bib_db, all_bib_entries, output_bib_path, deduplicate=True, removed_value_names=[], abbr_dict={}):
> ```
> 
> but the order within entries is not conserved so the diffs are still huge even if nothing changed.

Thank you so much for the comment and providing your insight into this sorting issue. I incorporated your suggestion into our code, which now provides users with the option to either keep the original order of the input bib entries or sort them alphabetically in the output file (PR #32). This update will for sure be included in our next release. 

We will look into the second problem mentioned above regarding the order within entries and work on it. Thanks again!

**Comment by mpariente** [comment]
Happy to be useful
