### ISSUE TITLE
The way `abbr.tsv` is loaded removes entries from the file

### ISSUE THREAD

**Issue by thomkeh** [yuchenlin/rebiber#31]
`abbr.tsv` has two entries for ICML:

```
Proc. of ICML | Proceedings of the .* International Conference on Machine Learning
Proc. of ICML | Machine Learning, Proceedings of the .* International Conference
```

but they are not both loaded, because in `load_abbr_tsv()` a dictionary is used such that the second entry overwrites the first one:
```python
ls = line.split("|")
if len(ls) == 2:
    abbr_dict[ls[0].strip()] = ls[1].strip()
```

I see two solutions here: either don't load the file into a dictionary (but just a list of tuples), or allow specifying *or* regex patterns (i.e., `(pattern1|pattern2)`) which would require using a different character than `|` to separate the left- and right-hand sides in `abbr.tsv`.

**Comment by yuchenlin** [comment]
Thank you! Fixed by this commit: https://github.com/yuchenlin/rebiber/commit/e718b69efba5d57fa584990e0151ba0eedae6b05
