### ISSUE TITLE
A more complete set of conferences

### ISSUE THREAD

**Issue by xgfs** [yuchenlin/rebiber#5]
Hi! It's a great tool. I have downloaded some other conferences of personal interest, and wanted to share them with others. There are some gaps in downloads here and there (specifically, for multi-volume conferences), but it's more complete than the one present in the repo. I have included more years as well.

The data is >400 MB uncompressed, and 30Mb compressed. I leave a link here for those who may find it useful.
http://tsitsul.in/data/confdata.zip

**Comment by yuchenlin** [comment]
Thank you very much for providing this useful data! I have integrated parts of them here!
