### ISSUE TITLE
Some refs disappear when generating in Hugging Face

### ISSUE THREAD

**Issue by blackboxo** [yuchenlin/rebiber#52]
Try this one in Hugging Face , it will generate an empty output.

@inproceedings{LocalAlgorithmFinding2013zhu,
title = {A Local Algorithm for Finding Well-Connected Clusters},
booktitle = {International {{Conference}} on {{Machine Learning}}},
author = {Zhu, Zeyuan Allen and Lattanzi, Silvio and Mirrokni, Vahab},
year = {2013},
pages = {396--404},
publisher = {{PMLR}}
}

**Comment by yuchenlin** [comment]
Hi, 

Thanks a lot for reporting this. Would you please try and see if you could help debug this with the current codebase? That would be super helpful! (I'll be quite busy this month).

Best,
Yuchen

**Comment by blackboxo** [comment]
No problem
