### ISSUE TITLE
ModuleNotFoundError: No module named 'bibtexparser'

### ISSUE THREAD

**Issue by fepegar** [yuchenlin/rebiber#7]
When trying to run the code in README.

**Comment by fepegar** [comment]
`tqdm` is also required.

**Comment by yuchenlin** [comment]
Hi @fepegar , we have this line `pip install bibtexparser` in the Readme. Did u try to install it before running the code? Thanks for the reminder on the `tqdm`! We will have a more comprehensive requirements.txt soon. Thanks!

**Comment by fepegar** [comment]
Oops, you're right. I went too fast!
