### ISSUE TITLE
Handle @string

### ISSUE THREAD

**Issue by scottyih** [yuchenlin/rebiber#8]
Nice tool!
It seems that currently it doesn't handle `@string` in BibTeX. Any plan to add this feature?

**Example**:

```
@string{emnlp = "Empirical Methods in Natural Language Processing (EMNLP)"}

@inproceedings{li2020efficient,
 title={Efficient One-Pass End-to-End Entity Linking for Questions},
 author={Li, Belinda Z. and Min, Sewon and Iyer, Srinivasan and Mehdad, Yashar and Yih, Wen-tau},
 booktitle=emnlp,
 year={2020}
}
```

**Comment by yuchenlin** [comment]
Hi Scott, 

Thanks for pointing it out. Yes, and to clarify, is the desired output like the following entry?


```bib
@string{emnlp = "Empirical Methods in Natural Language Processing (EMNLP)"}

@inproceedings{li2020efficient,
    title = "Efficient One-Pass End-to-End Entity Linking for Questions",
    author = "Li, Belinda Z.  and
      Min, Sewon  and
      Iyer, Srinivasan  and
      Mehdad, Yashar  and
      Yih, Wen-tau",
    booktitle = emnlp,
    month = nov,
    year = "2020",
    address = "Online",
    publisher = "Association for Computational Linguistics",
    url = "https://www.aclweb.org/anthology/2020.emnlp-main.522",
    doi = "10.18653/v1/2020.emnlp-main.522",
    pages = "6433--6441",
}
```
That is, if an input bib entry contains customized @string items, then we should keep it as it is (e.g.,  `booktitle = emnlp`, )while replacing other items?

Thanks!

**Comment by scottyih** [comment]
That's a good question and honestly I think it's personal choice (I'd probably just replace the whole bib entry). Right now the code breaks with exceptions, so as long as that doesn't happen, it's good! :p

**Comment by yuchenlin** [comment]
Got it! That would be much easier then. I just committed a simple fix and also appended the above example in the `example_input.bib`. It should fix the problem, but feel free to let me know if there are any problems. :)
